export const CryptoList = [
  { id: 0, name: "Acala", img: require("@/assets/img/copro/Acala.png") },
  { id: 1, name: "Acala EVM", img: require("@/assets/img/copro/Acala.png") },
  { id: 2, name: "Aeternity", img: require("@/assets/img/copro/Aeternity.avif") },
  { id: 3, name: "Agoric", img: require("@/assets/img/copro/Agoric.png") },
  { id: 4, name: "Aion", img: require("@/assets/img/copro/Aion.avif") },
  { id: 5, name: "Akash", img: require("@/assets/img/copro/Akash.avif") },
  { id: 6, name: "Algorand", img: require("@/assets/img/copro/Algorand.png") },
  { id: 7, name: "Aptos", img: require("@/assets/img/copro/Aptos.avif") },
  { id: 8, name: "Arbitrum", img: require("@/assets/img/copro/Arbitrum.avif") },
  { id: 9, name: "Aurora", img: require("@/assets/img/copro/Aurora.png") },
  { id: 10, name: "Avalanche C-Chain", img: require("@/assets/img/copro/Avalanche C-Chain.avif") },
  { id: 11, name: "Axelar", img: require("@/assets/img/copro/Axelar.png") },
  { id: 12, name: "BNB Smart Chain", img: require("@/assets/img/copro/bnb.avif") },
  { id: 13, name: "BandChain", img: require("@/assets/img/copro/BandChain.png") },
  { id: 14, name: "Base", img: require("@/assets/img/copro/Base.png") },
  { id: 15, name: "Binance", img: require("@/assets/img/copro/Binance.png") },
  { id: 16, name: "Bitcoin", img: require("@/assets/img/copro/Bitcoin.png") },
  { id: 17, name: "Bitcoin Cash", img: require("@/assets/img/copro/Bitcoin Cash.png") },
  { id: 18, name: "Bitcoin Gold", img: require("@/assets/img/copro/Bitcoin Gold.avif") },
  { id: 19, name: "Blast", img: require("@/assets/img/copro/Blast.png") },
  { id: 20, name: "Boba", img: require("@/assets/img/copro/Boba.png") },
  { id: 21, name: "BounceBit", img: require("@/assets/img/copro/BounceBit.avif") },
  { id: 22, name: "Cardano", img: require("@/assets/img/copro/Cardano.avif") },
  { id: 23, name: "Celo", img: require("@/assets/img/copro/Celo.png") },
  { id: 24, name: "Conflux eSpace", img: require("@/assets/img/copro/Conflux eSpace.avif") },
  { id: 25, name: "Cosmos", img: require("@/assets/img/copro/Cosmos.png") },
  { id: 26, name: "Cronos Chain", img: require("@/assets/img/copro/Cronos Chain.avif") },
  { id: 27, name: "CryptoOrg", img: require("@/assets/img/copro/CryptoOrg.avif") },
  { id: 28, name: "Dash", img: require("@/assets/img/copro/Dash.avif") },
  { id: 29, name: "Decred", img: require("@/assets/img/copro/Decred.avif") },
  { id: 30, name: "DigiByte", img: require("@/assets/img/copro/DigiByte.avif") },
  { id: 31, name: "Dogecoin", img: require("@/assets/img/copro/Dogecoin.avif") },
  { id: 32, name: "EOS", img: require("@/assets/img/copro/EOS.avif") },
  { id: 33, name: "Ethereum", img: require("@/assets/img/copro/eth.png") },
  { id: 34, name: "Ethereum Classic", img: require("@/assets/img/copro/Ethereum Classic.avif") },
  { id: 35, name: "Evmos", img: require("@/assets/img/copro/Evmos.avif") },
  { id: 36, name: "FIO", img: require("@/assets/img/copro/FIO.png") },
  { id: 37, name: "Fantom", img: require("@/assets/img/copro/Fantom.avif") },
  { id: 38, name: "Filecoin", img: require("@/assets/img/copro/Filecoin.avif") },
  { id: 39, name: "Firo", img: require("@/assets/img/copro/Firo.avif") },
  { id: 40, name: "GoChain", img: require("@/assets/img/copro/GoChain.avif") },
  { id: 41, name: "Greenfield", img: require("@/assets/img/copro/Greenfield.avif") },
  { id: 42, name: "Groestlcoin", img: require("@/assets/img/copro/Groestlcoin.avif") },
  { id: 43, name: "Harmony", img: require("@/assets/img/copro/Harmony.avif") },
  { id: 44, name: "ICON", img: require("@/assets/img/copro/ICON.avif") },
  { id: 45, name: "Internet Computer", img: require("@/assets/img/copro/Internet Computer.avif") },
  { id: 46, name: "IoTeX", img: require("@/assets/img/copro/IoTeX EVM.avif") },
  { id: 47, name: "IoTeX EVM.avif", img: require("@/assets/img/copro/IoTeX EVM.avif") },
  { id: 48, name: "Juno", img: require("@/assets/img/copro/Juno.avif") },
  { id: 49, name: "Kaia", img: require("@/assets/img/copro/Kaia.avif") },
  { id: 50, name: "Kava", img: require("@/assets/img/copro/Kava.avif") },
  { id: 51, name: "KavaEvm", img: require("@/assets/img/copro/Kava.avif") },
  { id: 52, name: "Kin", img: require("@/assets/img/copro/Kin.avif") },
  { id: 53, name: "KuCoin Community Chain", img: require("@/assets/img/copro/KuCoin Community Chain.avif") },
  { id: 54, name: "Linea", img: require("@/assets/img/copro/Linea.avif") },
  { id: 55, name: "Litecoin", img: require("@/assets/img/copro/Litecoin.avif") },
  { id: 56, name: "Manta Pacific", img: require("@/assets/img/copro/Manta Pacific.avif") },
  { id: 57, name: "Mantle", img: require("@/assets/img/copro/Mantle.avif") },
  { id: 58, name: "Merlin", img: require("@/assets/img/copro/Merlin.avif") },
  { id: 59, name: "Meter", img: require("@/assets/img/copro/Meter.avif") },
  { id: 60, name: "Metis", img: require("@/assets/img/copro/Metis.avif") },
  { id: 61, name: "Monad", img: "" },
  { id: 62, name: "Moonriver", img: require("@/assets/img/copro/Moonriver.avif") },
  { id: 63, name: "MultiversX", img: require("@/assets/img/copro/MultiversX.avif") },
  { id: 64, name: "NEAR", img: require("@/assets/img/copro/NEAR.avif") },
  { id: 65, name: "NEO", img: require("@/assets/img/copro/NEO.avif") },
  { id: 66, name: "NULS", img: require("@/assets/img/copro/NULS.png") },
  { id: 67, name: "Nano", img: require("@/assets/img/copro/Nano.avif") },
  { id: 68, name: "NativeEvmos", img: require("@/assets/img/copro/NativeEvmos.avif") },
  { id: 69, name: "NativeInjective", img: require("@/assets/img/copro/NativeInjective.avif") },
  { id: 70, name: "NativeZetaChain", img: require("@/assets/img/copro/NativeZetaChain.avif") },
  { id: 71, name: "Nebulas", img: require("@/assets/img/copro/Nebulas.avif") },
  { id: 72, name: "Neon", img: require("@/assets/img/copro/Neon.avif") },
  { id: 73, name: "Neutron", img: require("@/assets/img/copro/Neutron.avif") },
  { id: 74, name: "Nimiq", img: require("@/assets/img/copro/Nimiq.avif") },
  { id: 75, name: "OKX Chain", img: require("@/assets/img/copro/OKX Chain.avif") },
  { id: 76, name: "Ontology", img: require("@/assets/img/copro/Ontology.avif") },
  { id: 77, name: "OpBNB", img: require("@/assets/img/copro/OpBNB.avif") },
  { id: 78, name: "Optimism", img: require("@/assets/img/copro/Optimism.avif") },
  { id: 79, name: "Osmosis", img: require("@/assets/img/copro/Osmosis.avif") },
  { id: 80, name: "POA Network", img: require("@/assets/img/copro/POA Network.avif") },
  { id: 81, name: "Polkadot", img: require("@/assets/img/copro/Polkadot.avif") },
  { id: 82, name: "Polygon", img: require("@/assets/img/copro/Polygon.avif") },
  { id: 83, name: "Polygon zkEVM", img: require("@/assets/img/copro/Polygon.avif") },
  { id: 84, name: "Qtum", img: require("@/assets/img/copro/Qtum.png") },
  { id: 85, name: "Ravencoin", img: require("@/assets/img/copro/Ravencoin.png") },
  { id: 86, name: "Ronin", img: require("@/assets/img/copro/ronin.avif") },
  { id: 87, name: "Scroll", img: require("@/assets/img/copro/Scroll.avif") },
  { id: 88, name: "Sei", img: require("@/assets/img/copro/Sei.avif") },
  { id: 89, name: "Solana", img: require("@/assets/img/copro/sol.avif") },
  { id: 90, name: "Sonic", img: require("@/assets/img/copro/Sonic.avif") },
  { id: 91, name: "Stargaze", img: require("@/assets/img/copro/Stargaze.avif") },
  { id: 92, name: "Stellar", img: require("@/assets/img/copro/Stellar.avif") },
  { id: 93, name: "Stride", img: require("@/assets/img/copro/Stride.avif") },
  { id: 94, name: "sui", img: require("@/assets/img/copro/sui.avif") },
  { id: 95, name: "THORChain", img: require("@/assets/img/copro/THORChain.png") },
  { id: 96, name: "TON", img: require("@/assets/img/copro/TON.avif") },
  { id: 97, name: "Terra", img: require("@/assets/img/copro/Terra.avif") },
  { id: 98, name: "Tezos", img: require("@/assets/img/copro/Tezos.avif") },
  { id: 99, name: "Theta", img: require("@/assets/img/copro/Theta.avif") },
  { id: 100, name: "ThunderCore", img: require("@/assets/img/copro/ThunderCore.png") },
  { id: 101, name: "Tron", img: require("@/assets/img/copro/Tron.avif") },
  { id: 102, name: "VeChain", img: require("@/assets/img/copro/VeChain.avif") },
  { id: 103, name: "Viacoin", img: require("@/assets/img/copro/Viacoin.avif") },
  { id: 104, name: "Wanchain", img: require("@/assets/img/copro/Wanchain.avif") },
  { id: 105, name: "Waves", img: require("@/assets/img/copro/Waves.avif") },
  { id: 106, name: "XRP", img: require("@/assets/img/copro/XRP.avif") },
  { id: 107, name: "XRP", img: require("@/assets/img/copro/XRP.avif") },
  { id: 108, name: "Zcash", img: require("@/assets/img/copro/Zcash.avif") },
  { id: 109, name: "Zelcash", img: require("@/assets/img/copro/Zelcash.avif") },
  { id: 110, name: "Zeta EVM", img: require("@/assets/img/copro/Zeta EVM.avif") },
  { id: 111, name: "Zilliqa", img: require("@/assets/img/copro/Zilliqa.avif") },
  { id: 112, name: "Zksync", img: require("@/assets/img/copro/Zksync.avif") },
  { id: 113, name: "xDai", img: require("@/assets/img/copro/xDai.png") }
];
